#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/tests.v1.schema.json

test_format = 1.0

[default]

    test_upgrade_from.d3ce265.name = "Non pre-built version"
    test_upgrade_from.d3ce265.args.mongo_version = "7.0"
