#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

# Keep this path for calling _common.sh inside the execution's context of backup and restore scripts
source ../settings/scripts/_common.sh
source /usr/share/yunohost/helpers

#=================================================
# DECLARE DATA AND CONF FILES TO BACKUP
#=================================================
ynh_print_info --message="Declaring files to be backed up..."

#=================================================
# BACKUP THE APP MAIN DIR
#=================================================

ynh_backup --src_path="$install_dir"

#=================================================
# SYSTEM CONFIGURATION
#=================================================

# Backup the nginx configuration
ynh_backup --src_path="/etc/nginx/conf.d/$domain.d/$app.conf"

# Backup the systemd service unit
ynh_backup --src_path="/etc/systemd/system/$app.service"

# Backup the logrotate configuration
ynh_backup --src_path="/etc/logrotate.d/$app"

ynh_backup --src_path="/var/log/$app/"

#=================================================
# DONT BACKUP THE MONGO DATABASE
#=================================================
ynh_print_warn --message="Mongo data is NOT backed up by this application. Each application using it is backing up its own database..."

#=================================================
# END OF SCRIPT
#=================================================

ynh_print_info --message="Backup script completed for $app. (YunoHost will then actually copy those files to the archive)."
