#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source ynh_mongo_db__2
source /usr/share/yunohost/helpers

#=================================================
# STANDARD REMOVE
#=================================================
# REMOVE SERVICE INTEGRATION IN YUNOHOST
#=================================================

# Remove the service from the list of services known by YunoHost (added from `yunohost service add`)
if ynh_exec_warn_less yunohost service status $app >/dev/null; then
    ynh_script_progression --message="Removing $app service integration..." --weight=1
    yunohost service remove "$app"
fi

#=================================================
# REMOVE SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression --message="Removing system configurations related to $app..." --weight=1

# Remove the dedicated systemd config
ynh_remove_systemd_config

# Remove the app-specific logrotate config
ynh_remove_logrotate

# Remove the dedicated NGINX config
ynh_remove_nginx_config

# Remove the log files
ynh_secure_remove --file="/var/log/$app"

#=================================================
# REMOVE DEPENDENCIES
#=================================================
ynh_script_progression --message="Removing NodeJS..." --weight=1

# Remove the version of Nodejs used if needed
ynh_remove_nodejs

if [ "$mongo_version" != "None" ]; then
    ynh_script_progression --message="Removing the MongoDB database..."
    ynh_remove_mongo
fi

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Removal of $app completed" --last
