#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers
source _mongo_helper.sh

#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression "Stopping $app's systemd service..."

ynh_systemctl --service="$app" --action="stop"

#=================================================
# INSTALL DEPENDENCIES
#=================================================
ynh_script_progression "Installing NodeJS & Yarn"

ynh_nodejs_install

# Install mongo server only if asked to
if [ "$mongo_version" != "None" ]; then
    ynh_script_progression "Installing MongoDB..."
    ynh_install_mongo
else
    # gives the mongo service name for the rest of installation
    mongodb_servicename=mongod
fi

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Upgrading source files..."

# Download, check integrity, uncompress and patch the source from amd64.src
ynh_setup_source --full_replace --dest_dir="$install_dir"

cp "$install_dir/config.default.js" "$install_dir/config.js"
chown "$app:$app" "$install_dir/config.js"

ynh_config_add --template=".env" --destination="$install_dir/.env"

#=================================================
# BUILD NODEJS CODE
#=================================================
ynh_script_progression "Installing Yarn and Building application..."

# Build using Yarn
pushd "$install_dir"
        # We must use npm to install yarn but without installing other dependencies as npm fails with them
    if [ -f "package.json" ]; then
        mv package.json package.json.mov

    fi
    _install_yarn
    if [ -f "package.json.mov" ]; then
        mv package.json.mov package.json

    fi
      # patch the version of html-entities until it is fixed upstream
    ynh_replace --match="\"html-entities\": \"^2.3.3\"" --replace="\"html-entities\": \"~2.3.3\"" --file=package.json
    ynh_exec_as_app "$ynh_yarn" install
    ynh_exec_as_app $nodejs_dir/npm run build
popd

#=================================================
# REAPPLY SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Upgrading system configurations related to $app..."

# Create a dedicated NGINX config
ynh_config_add_nginx

# Create a dedicated systemd config
ynh_config_add_systemd
yunohost service add "$app" --description="Mongo Express to easily administer your Mongo databases" --log="/var/log/$app/$app.log"

# Use logrotate to manage app-specific logfile(s)
ynh_config_add_logrotate

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service="$app" --action="start"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
